---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primeapp
  labels:
    app: primeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: primeapp
  template:
    metadata:
      labels:
        app: primeapp
    spec:
      containers:
      - name: primeapp-container
        image: ajay048/primeapp:63
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
...
