---
apiVersion: v1
kind: Service
metadata:
  name: primeapp
  labels:
    app: primeapp
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: primeapp
  type: LoadBalancer
...
